config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :products
  root 'products#index'
  
  get 'about', to: 'products#about', as: :about

  get 'contact_us', to: 'products#contact_us', as: :contact_us

end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :products

end

app/models/product.rb
class Product < ActiveRecord::Base

	has_many :reviews
	belongs_to :category
	
	validates :name, :description, presence: true
	validates :price_in_cents, numericality: {only_integer: true, greater_than: 0}

	def formatted_price
		sprintf("%.2f", price_in_dollars)
	end

	def price_in_dollars=(dollars)
		self.price_in_cents=(dollars.to_f*100).to_i
	end

	def price_in_dollars
		return nil if price_in_cents.nil?
		price_in_cents/100.0
	end


end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception





end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about_us

	end

	def contact_us

	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]


  def about
  end

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @review = Review.new
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price_in_dollars, :category_id)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:comment, :product_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Congo Marketplace</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

  <link rel="stylesheet" href="./assets/stylesheets/products.css">

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

  <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
</head>
<body>

<meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    <link type="text/css" rel="stylesheet" href="./testserver.css">
    
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

    <script src="./jquery-min.js"></script>

   

<div class="container-fluid" id="topbar">
  <div class="jumbotron" id="jumbo">
    <h1 id="header">CONGO</h1>
    <span class="lead">The LAB is having a firesale!</span>
    <div id="nav-bar">
	    <ul>
	    	<li><%= link_to "Home", products_path %></li>
	    	<li><%= link_to "About Congo", about_us_path %></li>
	    </ul>
  	</div>
	</div>
</div>


<%= yield %>

</body>
</html>

app/views/pages/about_us.html.erb
	<div class="well well">
		<p>
			Welcome to Congo! <br>
			Congo is a marketplace where any individual can purchase or sell a product from the LAB. We have a wide variety of interesting items that include chairs, broken espresso machines, "Imported" Dark Dog energy drink coolers, and other random stuff from around this awesome space.
			
		</p>
	</div>

	<center><div class="profile_pic">
		<ul>
			<li ><img class="gabe" src="https://media.licdn.com/mpr/mpr/shrink_200_200/AAEAAQAAAAAAAANfAAAAJDc5MDA1YzE5LTc0MGYtNDc1OC04ZmFkLTZiOTVhMjA4NTc0Mw.jpg"></li>
			<li><img  class="carlos" src="https://media.licdn.com/mpr/mpr/shrinknp_200_200/p/3/005/03f/3d5/1417ea0.jpg"></li>
			<li><img  class="jeff" src="https://media.licdn.com/mpr/mpr/shrink_200_200/AAEAAQAAAAAAAAMxAAAAJGQ2NzFjY2JiLWNkNDAtNGRiMy1hZDQ0LWUxNmEwMDJkODY1MQ.jpg"></li>
		</ul>
		<ul class="profile_name">
			<li> Gabriel Noboa </li>
			<li>Carlos Socorro</li>
			<li>Jeff Shapiro</li>
		</ul>

		<ul class="email_us">
			<li><buttom type="button" class="btn btn-default" aria-label="Left Align" id="button-i-want-to-move"><span><a href="mailto:gabriel.g.noboa@gmail.com" target="blank">Email Gabe </a></span></li>

		  <li><buttom type="button" class="btn btn-default" aria-label="Left Align" id="button-i-want-to-move"><span><a href="mailto:carlosrsocorro@gmail.com" target="blank"> Email Carlos</a></span></li>

		  <li><buttom type="button" class="btn btn-default" aria-label="Left Align" id="button-i-want-to-move"><span><a href="mailto:codesheff@gmail.com" target="blank"> Email Jeff</a></span></li>
		</ul>

app/views/pages/contact_us.html.erb
hello contact us

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price_in_dollars %><br>
    <%= f.text_field :price_in_dollars  %>
  </div>
  
  <div class="field">
    <%= f.label :category %><br>
    <%= f.collection_select(:category_id, Category.order(:catname), :id, :catname, include_blank: true) %>
  </div>
  <div class="field">
    <%= f.label :product_image_url %><br>
    <%= f.text_field :imageurl  %>
  </div>

<div class="create_actions">
  <center><buttom type="button" aria-label="Left Align" id="button-i-want-to-move">
    <span><%= f.submit :class => "btn btn-default" %></span></center>
</div>

  <% end %>

app/views/products/about.html.erb
<h1>YOU ARE ON THE ABOUT PAGE</h1>

app/views/products/contact_us.html.erb
<h1>YOU ARE ON THE CONTACT US PAGE</h1>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js">
</script>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

<link type="text/css" rel="stylesheet" href="./assets/stylesheets/products.css">

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>



<p id="notice"><%= notice %></p>


<!-- <div class="container-fluid" id="topbar">
  <div class="jumbotron" id="jumbo">
    <h1 id="header">CONGO</h1>
    <span class="lead">About Us </span>     
  </div>
  <div class='catbar'> 
  <div id="new_product"><%= link_to 'New Product', new_product_path %></div>
</div> 
</div> -->
<span class="list_products">
<h1 style="text-align: center;">List of Products</h1>
</span>

<center><buttom type="button" class="btn btn-default" aria-label="Left Align" id="button-i-want-to-move">
  <span><%= link_to 'New Product', new_product_path %></span></center>
  <div class="text-center">
    <div id="dropdown1">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
      Product Category
      <span class="caret"></span>
    </button>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
        <% @categories.each do |cat| %>
        <li roll="presentation"><%= cat.catname %></li>
      <% end %>
      </ul>
    </div>
  </div>



<div class="row" id="rowclass">
        <% @products.each do |product| %>
  <div id="mainwrapper">

  <div class="col-md-4" id="col">

      <div id="box-1" class="box">
        <img src="<%=product.imageurl%>"atl= "imgbox" height=100%; width:100%; />
        <span class="caption full-caption">
        <h3><%=product.name%></h4>
        <p><%=product.description%></p>
        <p>$<%=product.formatted_price%></p>
        </span>
 
    </div>

  </div>
      <% end %>
</div>
</div>







<!-- <table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr> -->
  <!-- </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.formatted_price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="row">
  <div id="mainwrapper">
  <div class="col-md-4">
      <div id="box-1" class="box">
        <img id="image-1" src="http://i.imgur.com/YJzrpwW.jpg" atl= "imgbox" height=100%; width:100%; />
        <span class="caption full-caption">
        <h3>Turbo Air Refrigerator</h3><h4>price</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua.</p>
        </span>
    </div>
  </div>
  <div class="col-md-4">
      <div id="box-2" class="box">
        <img id="image-2" src="http://i.imgur.com/vO7bg9l.jpg" atl= "imgbox" height=100%; width:100%; />
        <span class="caption full-caption">
        <h3>Coffee Thermo</h3><h4>price</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua.</p>
        </span>
    </div>
  </div>
  <div class="col-md-4">
      <div id="box-3" class="box">
        <img id="image-3" src="http://i.imgur.com/fD9drGX.jpg" atl= "imgbox" height=100%; width:100%;  />
        <span class="caption full-caption">
        <h3>Wynwood Brewing Growler</h3><h4>price</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        </span>
    </div>
  </div>
</div>



<br>
 -->

app/views/products/new.html.erb
<div class="new_product_tittle">
<div class= "text-center"><h1>New Product</h1></div>
</div>

<div class= "text-center"><%= render 'form' %></div>


<center><buttom type="button" class="btn btn-default" aria-label="Left Align" id="button-i-want-to-move">
	<span><%= link_to 'Back', products_path %></span></center>

app/views/products/show.html.erb
<div class="text-center">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  $<%= @product.formatted_price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category.catname %>
</p>
</div>

<div class="text-center">
<h3>Reviews</h3>
	<% @product.reviews.each do |review| %> <p>
	<%= review.comment %>
	<br>
  <%= link_to "Edit", edit_review_path(review) %>
	Added on: <%= time_ago_in_words(review.created_at) %>
	</p> 
<% end %>


<div class="text-center">
<h3>New Review</h3>
<%= render 'reviews/form' %>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <% if @product.nil? %> 
  <% else %>
    <%= f.hidden_field :product_id, value: @product.id %>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<div class="text-center">
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<div class="text-center">
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>
</div>
<div class="text-center">
  <tbody class="text-center">
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.comment %></td>
        <td><%= review.product.name %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

</table>

<br>

<%= link_to 'New Review', new_review_path %>
</div>
</div>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<div class="text-center">
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
  <strong>Product:</strong>
  <%= @review.product.name %>
</p>
<div class="text-center">
<%= link_to 'Edit', edit_review_path(@review) %> |
	<% if @review.product.nil? %>
		<%= link_to 'Back', reviews_path %> 
	<% else %>
		<%= link_to 'Back', @review.product %> 
	<% end %>